### ISSUE TITLE
Anilist commands

### ISSUE THREAD

**Issue by ToxicMushroom** [Melijn/melijn-bot#16]
Allow linking your anilist profile to your discord account
Commands for viewing information about 
- [x] animes
- [x] mangas
- [x] characters
- [x] user profiles by name or discord user (and then lookup the linked user)
- [x] search versions that show the first 5-10 matches of the above types ^ (useful when media or characters have similar names)

/Open to additions\

**Comment by zeroeightysix** [comment]
gimme
