### ISSUE TITLE
Update README with development instructions

### ISSUE THREAD

**Issue by zeroeightysix** [Melijn/melijn-bot#17]
As it is desirable to attract external developers to help improve melijn, instructions on how to run the bot should be added to the README.

**Comment by ToxicMushroom** [comment]
I didn't mean to close this, please check if the current changes suffice or if more information is required.

**Comment by zeroeightysix** [comment]
> I didn't mean to close this, please check if the current changes suffice or if more information is required.

The current README suffices.
