### ISSUE TITLE
Docker image crashes on startup

### ISSUE THREAD

**Issue by mind-overflow** [Melijn/melijn-bot#31]
I cloned the repo and edited the env files and docker-compose.yml to fit my configuration, however, after starting the server, Melijn gets in a crash loop with this error:
```
melijn             | Invalid maximum heap size: -Xmx
melijn             | Error: Could not create the Java Virtual Machine.
melijn             | Error: A fatal exception has occurred. Program will exit.
```

I'm guessing I have to set the maximum allowed JVM heap size somewhere, but I can't find any ENV variable nor bootup string/arguments for it.

**Comment by ToxicMushroom** [comment]
Hi thanks for trying out our project.
Your assumption is correct, the docker file expects the env varibale RAM_LIMIT to be set (e.g. 128MB).

**Comment by ToxicMushroom** [comment]
Should be addressed by [854957b](https://github.com/Melijn/melijn-bot/commit/854957b68981c1b9e329cb3cdbedede6968eaf61)

**Comment by mind-overflow** [comment]
Thanks for the heads up! And sorry if the first message seemed a bit rushed, it was a pretty busy day. I ran into another issue that I was however able to temporarily mitigate, but this issue is solved. Thanks again, I really like Melijn - and being able to look at its source code and tinker with it is definitely fun! Keep up the good work :)

**Comment by ToxicMushroom** [comment]
Glad to see that you're enjoying the project 😁
